manifest:
  tag: pojntfx/ipxebuilderd:latest
chart:
  srcDir: charts/ipxebuilderd
  distDir: .bin/chart
  cleanGlobs:
    - .bin/chart/ipxebuilderd-*.tgz
    - charts/ipxebuilderd/charts
platforms:
  - platform: linux/amd64
    chartProfiles:
      production: ipxebuilderd
      development: ipxebuilderd-dev
    assets:
      build:
        command: go generate ./... && GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -tags netgo -ldflags '-extldflags "-static"' -o .bin/ipxebuilderd-linux-amd64 cmd/ipxebuilderd/main.go
        tag: pojntfx/ipxebuilderd:linux-amd64
        context: .
        file: Dockerfile
      pathInImage: /usr/local/bin/ipxebuilderd
      distPath: .bin/ipxebuilderd-linux-amd64
      cleanGlobs:
        - .bin/ipxebuilderd-linux-amd64
        - pkg/proto/generated/proto/*pb*
    starters:
      lang:
        command: go run cmd/ipxebuilderd/main.go
      assets:
        command: .bin/ipxebuilderd-linux-amd64
    tests:
      unit:
        lang:
          command: go test ./...
          tag: pojntfx/ipxebuilderd-unittest:linux-amd64
          context: .
          file: Dockerfile.unitTestLang
      integration:
        lang:
          command: go run cmd/ipxebuilderd/main.go --help
          tag: pojntfx/ipxebuilderd-integrationtest-lang:linux-amd64
          context: .
          file: Dockerfile.integrationTestLang
        image:
          command: docker run --platform linux/amd64 -e TARGETPLATFORM=linux/amd64 pojntfx/ipxebuilderd:linux-amd64 /usr/local/bin/ipxebuilderd --help
          tag: pojntfx/ipxebuilderd-integrationtest-image:linux-amd64
          context: .
          file: Dockerfile.integrationTestImage
        assets:
          command: .bin/ipxebuilderd-linux-amd64 --help
          tag: pojntfx/ipxebuilderd-integrationtest-assets:linux-amd64
          context: .
          file: Dockerfile.integrationTestAssets
        chart:
          command: helm install --name ipxebuilderd .bin/chart/ipxebuilderd-*.tgz && helm delete ipxebuilderd
          tag: pojntfx/ipxebuilderd-integrationtest-chart:linux-amd64
          context: .
          file: Dockerfile.integrationTestChart
  - platform: linux/arm64
    chartProfiles:
      production: ipxebuilderd
      development: ipxebuilderd-dev
    assets:
      build:
        command: go generate ./... && GOOS=linux GOARCH=arm64 CGO_ENABLED=0 go build -tags netgo -ldflags '-extldflags "-static"' -o .bin/ipxebuilderd-linux-arm64 cmd/ipxebuilderd/main.go
        tag: pojntfx/ipxebuilderd:linux-arm64
        context: .
        file: Dockerfile
      pathInImage: /usr/local/bin/ipxebuilderd
      distPath: .bin/ipxebuilderd-linux-arm64
      cleanGlobs:
        - .bin/ipxebuilderd-linux-arm64
        - pkg/proto/generated/proto/*pb*
    starters:
      lang:
        command: go run cmd/ipxebuilderd/main.go
      assets:
        command: .bin/ipxebuilderd-linux-arm64
    tests:
      unit:
        lang:
          command: go test ./...
          tag: pojntfx/ipxebuilderd-unittest:linux-arm64
          context: .
          file: Dockerfile.unitTestLang
      integration:
        lang:
          command: go run cmd/ipxebuilderd/main.go --help
          tag: pojntfx/ipxebuilderd-integrationtest-lang:linux-arm64
          context: .
          file: Dockerfile.integrationTestLang
        image:
          command: docker run --platform linux/arm64 -e TARGETPLATFORM=linux/arm64 pojntfx/ipxebuilderd:linux-arm64 /usr/local/bin/ipxebuilderd --help
          tag: pojntfx/ipxebuilderd-integrationtest-image:linux-arm64
          context: .
          file: Dockerfile.integrationTestImage
        assets:
          command: .bin/ipxebuilderd-linux-arm64 --help
          tag: pojntfx/ipxebuilderd-integrationtest-assets:linux-arm64
          context: .
          file: Dockerfile.integrationTestAssets
        chart:
          command: helm install --name ipxebuilderd .bin/chart/ipxebuilderd-*.tgz && helm delete ipxebuilderd
          tag: pojntfx/ipxebuilderd-integrationtest-chart:linux-arm64
          context: .
          file: Dockerfile.integrationTestChart
