# syntax=docker/dockerfile:experimental
FROM --platform=$TARGETPLATFORM docker:stable
WORKDIR /app
ARG TARGETPLATFORM

RUN apk update
RUN apk add curl

RUN curl -Lo dibs https://github.com/pojntfx/dibs/releases/latest/download/dibs-linux-amd64
RUN chmod +x dibs
RUN mv dibs /usr/local/bin/dibs

COPY ./.dibs.yml ./.dibs.yml
COPY ./cmd ./cmd
COPY ./pkg ./pkg

EXPOSE 1440

CMD dibs pipeline test integration image
