apiVersion: skaffold/v1
kind: Config
metadata:
  name: ipxebuilderd
profiles:
  - name: ipxebuilderd
    build:
      artifacts:
        - image: pojntfx/ipxebuilderd
          context: .
          docker:
            dockerfile: Dockerfile
      local:
        useBuildkit: true
    deploy:
      helm:
        releases:
          - name: ipxebuilderd
            chartPath: charts/ipxebuilderd
            values:
              meta.image: pojntfx/ipxebuilderd
  - name: ipxebuilderd-dev
    build:
      artifacts:
        - image: pojntfx/ipxebuilderd-dev
          context: .
          docker:
            dockerfile: Dockerfile.dev
          sync:
            infer:
              - "**/*" # Re-deploy manually to apply k8s changes
      local:
        useBuildkit: true
    deploy:
      helm:
        releases:
          - name: ipxebuilderd-dev
            chartPath: charts/ipxebuilderd
            values:
              meta.image: pojntfx/ipxebuilderd-dev
            setValues:
              meta.dev: true
            setValueTemplates:
              meta.target: "{{ .TARGET }}"
              meta.platform: "{{ .TARGETPLATFORM }}"
              meta.debug: "{{ .DEBUG }}"
