apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipxebuilderd{{ if .Values.meta.dev }}-dev{{ end }}
spec:
  selector:
    matchLabels:
      app: ipxebuilderd{{ if .Values.meta.dev }}-dev{{ end }}
  template:
    metadata:
      labels:
        app: ipxebuilderd{{ if .Values.meta.dev }}-dev{{ end }}
    spec:
      containers:
        - name: ipxebuilderd{{ if .Values.meta.dev }}-dev{{ end }}
          image: {{ .Values.meta.image }}
          {{ if not .Values.meta.dev }}
          resources:
            limits:
              memory: {{ .Values.resources.memory }}
              cpu: {{ .Values.resources.cpu }}
          {{ end }}
          ports:
            - containerPort: 1440
  {{ if .Values.meta.dev }}

---
apiVersion: v1
kind: Service
metadata:
  name: ipxebuilderd-dev
spec:
  selector:
    app: ipxebuilderd-dev
  type: NodePort
  ports:
    - name: grpc
      port: 31440
      targetPort: 1440
      nodePort: {{ .Values.ingress.nodePort }}
  {{ else }}

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: ipxebuilderd
spec:
  selector:
    app: ipxebuilderd
  maxReplicas: {{ .Values.resources.maxReplicas }}
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ipxebuilderd
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 60

---
apiVersion: v1
kind: Service
metadata:
  name: ipxebuilderd
spec:
  selector:
    app: ipxebuilderd
  ports:
    - name: grpc
      port: 1440
      targetPort: 1440

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ipxebuilderd
  annotations:
    ingress.kubernetes.io/protocol: h2c
spec:
  rules:
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: ipxebuilderd
              servicePort: grpc
  {{ end }}
