apiVersion: v1
kind: ConfigMap
metadata:
  name: ipxebuilder-{{ .Release.Name }}{{ if .Values.meta.dev }}-dev{{ end }}
data:
  DIBS_TARGET: "{{ .Values.meta.target }}"
  TARGETPLATFORM: "{{ .Values.meta.platform }}"
  IPXEBUILDERD_IPXEBUILDERD_S3HOSTPORTPUBLIC: "{{ if .Values.meta.dev }}{{ .Release.Name }}-minio:9000{{ else }}{{ (index .Values.minio.ingress.hosts 0).name }}{{ end }}"
  IPXEBUILDERD_IPXEBUILDERD_S3HOSTPORT: "{{ .Release.Name }}-minio:9000"
  IPXEBUILDERD_IPXEBUILDERD_S3ACCESSKEY: "{{ .Values.minio.accessKey.password }}"
  IPXEBUILDERD_IPXEBUILDERD_S3SECRETKEY: "{{ .Values.minio.secretKey.password }}"
  IPXEBUILDERD_IPXEBUILDERD_S3BUCKET: "{{ .Values.S3.bucket }}"
  IPXEBUILDERD_IPXEBUILDERD_S3SECURE: "{{ .Values.S3.secure }}"
  {{ if and .Values.meta.dev .Values.meta.debug }}
  DIBS_DEBUG: "true"
  {{end}}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipxebuilderd-{{ .Release.Name }}{{ if .Values.meta.dev }}-dev{{ end }}
spec:
  selector:
    matchLabels:
      app: ipxebuilderd-{{ .Release.Name }}{{ if .Values.meta.dev }}-dev{{ end }}
  template:
    metadata:
      labels:
        app: ipxebuilderd-{{ .Release.Name }}{{ if .Values.meta.dev }}-dev{{ end }}
    spec:
      containers:
        - name: ipxebuilderd{{ if .Values.meta.dev }}-dev{{ end }}
          image: {{ .Values.meta.image }}
          envFrom:
            - configMapRef:
                name: ipxebuilder-{{ .Release.Name }}{{ if .Values.meta.dev }}-dev{{ end }}
          {{ if not .Values.meta.dev }}
          resources:
            limits:
              memory: {{ .Values.resources.memory }}
              cpu: {{ .Values.resources.cpu }}
          {{ end }}
          ports:
            - containerPort: 1440
            {{ if and .Values.meta.dev .Values.meta.debug }}
            - containerPort: {{ .Values.meta.debugPort }}
            {{end}}
  {{ if .Values.meta.dev }}

---
apiVersion: v1
kind: Service
metadata:
  name: ipxebuilderd-{{ .Release.Name }}-dev
spec:
  selector:
    app: ipxebuilderd-{{ .Release.Name }}-dev
  type: NodePort
  ports:
    - name: grpc
      port: 31440
      targetPort: 1440
      nodePort: {{ .Values.ingress.nodePort }}
    - name: debug
      port: {{ .Values.meta.debugNodePort }}
      targetPort: {{ .Values.meta.debugPort }}
      nodePort: {{ .Values.meta.debugNodePort }}
  {{ else }}

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: ipxebuilderd-{{ .Release.Name }}
spec:
  maxReplicas: {{ .Values.resources.maxReplicas }}
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ipxebuilderd-{{ .Release.Name }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 60

---
apiVersion: v1
kind: Service
metadata:
  name: ipxebuilderd-{{ .Release.Name }}
spec:
  selector:
    app: ipxebuilderd-{{ .Release.Name }}
  ports:
    - name: grpc
      port: 1440
      targetPort: 1440

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ipxebuilderd-{{ .Release.Name }}
  annotations:
    ingress.kubernetes.io/protocol: h2c
spec:
  rules:
    - host: {{ .Values.ingress.domain }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}
            backend:
              serviceName: ipxebuilderd-{{ .Release.Name }}
              servicePort: grpc
  {{ end }}
